# Generated by Django 4.1 on 2022-10-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('description2', models.CharField(max_length=255, null=True, verbose_name='Краткое описание 2')),
                ('description3', models.CharField(max_length=255, null=True, verbose_name='Площадь')),
                ('description4', models.CharField(max_length=255, null=True, verbose_name='Город')),
                ('description5', models.CharField(max_length=255, null=True, verbose_name='Архитекторы')),
                ('title2', models.CharField(max_length=255, null=True, verbose_name='Заголовок 2')),
                ('description6', models.CharField(max_length=255, null=True, verbose_name='Краткое описание 2')),
                ('title3', models.CharField(max_length=255, null=True, verbose_name='Приписка к проекту')),
                ('title4', models.CharField(max_length=255, null=True, verbose_name='Заголовок 2')),
                ('title5', models.CharField(max_length=255, null=True, verbose_name='Заголовок 2')),
                ('image1', models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка')),
                ('image2', models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка')),
                ('image3', models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка')),
                ('image4', models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка')),
                ('image5', models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка')),
                ('image6', models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка')),
                ('image7', models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка')),
                ('image8', models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка')),
                ('image9', models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('publish', models.BooleanField(default=True, verbose_name='Публикация')),
                ('main', models.BooleanField(default=False, verbose_name='На главной')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_project', to='services.services')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
