# Generated by Django 4.1 on 2022-10-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='description2',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание 2'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description3',
            field=models.CharField(max_length=255, null=True, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description4',
            field=models.CharField(max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description5',
            field=models.CharField(max_length=255, null=True, verbose_name='Архитекторы'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description6',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание 2'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image1',
            field=models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image2',
            field=models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image3',
            field=models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image4',
            field=models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image5',
            field=models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image6',
            field=models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image7',
            field=models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image8',
            field=models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image9',
            field=models.ImageField(default='project/no_image.jpg', null=True, upload_to='project/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='projects',
            name='main',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title2',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title3',
            field=models.CharField(max_length=255, null=True, verbose_name='Приписка к проекту'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title4',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title5',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
