# Generated by Django 4.1 on 2022-10-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='services',
            new_name='services_project',
        ),
    ]
