# Generated by Django 4.1 on 2022-10-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_services_projects_services_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title6',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title7',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title8',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title9',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='services',
            name='image1',
            field=models.ImageField(default='services/no_image.jpg', null=True, upload_to='services/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='services',
            name='image2',
            field=models.ImageField(default='services/no_image.jpg', null=True, upload_to='services/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='services',
            name='image3',
            field=models.ImageField(default='services/no_image.jpg', null=True, upload_to='services/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='services',
            name='image4',
            field=models.ImageField(default='services/no_image.jpg', null=True, upload_to='services/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='services',
            name='image5',
            field=models.ImageField(default='services/no_image.jpg', null=True, upload_to='services/', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='services',
            name='image6',
            field=models.ImageField(default='services/no_image.jpg', null=True, upload_to='services/', verbose_name='Главная картинка'),
        ),
    ]
