# Generated by Django 4.1 on 2022-10-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_projects_title6_projects_title7_projects_title8_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description2',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание 1'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название проекта'),
        ),
    ]
