# Generated by Django 4.1 on 2022-10-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_projects_text_projects_title10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='year',
            field=models.CharField(max_length=255, null=True, verbose_name='Год проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description2',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст 1'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description6',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст к заголовку 2'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title10',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст к заголовку 4'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title2',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title5',
            field=models.CharField(max_length=255, null=True, verbose_name='Приписка к картинке 8'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title6',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок 3'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title7',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст к заголовку 3'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title8',
            field=models.CharField(max_length=255, null=True, verbose_name='Приписка к картинке 9'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title9',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок 4'),
        ),
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Не изменять'),
        ),
    ]
