# Generated by Django 4.1 on 2022-10-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_projects_year_alter_projects_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image7',
            field=models.ImageField(default='services/no_image.jpg', null=True, upload_to='services/', verbose_name='Картинка 7'),
        ),
    ]
