# Generated by Django 4.1 on 2022-10-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_services_image7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description6',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст к заголовку 2'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title10',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст к заголовку 4'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title7',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст к заголовку 3'),
        ),
    ]
