# Generated by Django 4.1 on 2022-10-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вакансия')),
                ('type_employment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип занятости')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('publish', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Обязанности')),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='vacancies.vacancies')),
            ],
            options={
                'verbose_name': 'Обязанности',
                'verbose_name_plural': 'Обязанности',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Требования')),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='vacancies.vacancies')),
            ],
            options={
                'verbose_name': 'Требования',
                'verbose_name_plural': 'Требования',
            },
        ),
        migrations.CreateModel(
            name='Circumstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Условия')),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circumstances', to='vacancies.vacancies')),
            ],
            options={
                'verbose_name': 'Условия',
                'verbose_name_plural': 'Условия',
            },
        ),
    ]
