# Generated by Django 4.1 on 2022-10-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вакансия')),
                ('type_employment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип занятости')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('circumstances', models.TextField(blank=True, null=True, verbose_name='Условия')),
                ('publish', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
        ),
    ]
