# Generated by Django 4.1 on 2022-10-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(max_length=25, verbose_name='phone')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('сhecked', models.BooleanField(default=False, verbose_name='сhecked')),
            ],
            options={
                'verbose_name': 'Форма вакансии',
                'verbose_name_plural': 'Форма вакансии',
            },
        ),
    ]
