# Generated by Django 4.1 on 2022-10-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': 'Вакансии', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='circumstances',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='responsibilities',
        ),
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='vacancies.vacancies')),
            ],
            options={
                'verbose_name': 'Обязанности',
                'verbose_name_plural': 'Обязанности',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='vacancies.vacancies')),
            ],
            options={
                'verbose_name': 'Требования',
                'verbose_name_plural': 'Требования',
            },
        ),
        migrations.CreateModel(
            name='Circumstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circumstances', to='vacancies.vacancies')),
            ],
            options={
                'verbose_name': 'Условия',
                'verbose_name_plural': 'Условия',
            },
        ),
    ]
