# Generated by Django 4.1 on 2022-10-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circumstances',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='responsibilities',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Обязанности'),
        ),
    ]
