# Generated by Django 4.1 on 2022-10-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image1', models.ImageField(default='blog/no_image.jpg', null=True, upload_to='blog/', verbose_name='Главная картинка')),
                ('text1', models.TextField(blank=True, null=True, verbose_name='Первая часть текста')),
                ('image2', models.ImageField(default='blog/no_image.jpg', null=True, upload_to='blog/', verbose_name='Вторая картинка')),
                ('text2', models.TextField(blank=True, null=True, verbose_name='Вторая часть текста')),
                ('image3', models.ImageField(default='blog/no_image.jpg', null=True, upload_to='blog/', verbose_name='Третья картинка')),
                ('publish', models.BooleanField(default=True, verbose_name='Публикация')),
                ('main', models.BooleanField(default=False, verbose_name='Главная новость')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
    ]
