# Generated by Django 4.1 on 2022-10-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main',
            field=models.BooleanField(default=False, unique=True, verbose_name='Главная новость'),
        ),
    ]
