# Generated by Django 4.1 on 2022-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главная новость'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
