# Generated by Django 4.1 on 2022-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_main_blog_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главная новость'),
        ),
    ]
