# Generated by Django 4.1 on 2022-10-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(max_length=25, verbose_name='phone')),
                ('сhecked', models.BooleanField(default=False, verbose_name='сhecked')),
            ],
        ),
        migrations.CreateModel(
            name='PartnersForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(max_length=25, verbose_name='phone')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('сhecked', models.BooleanField(default=False, verbose_name='сhecked')),
            ],
        ),
    ]
