# Generated by Django 4.1 on 2022-09-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexForm',
        ),
    ]
