# Generated by Django 4.1 on 2022-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0002_delete_indexform'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(max_length=25, verbose_name='phone')),
                ('сhecked', models.BooleanField(default=False, verbose_name='сhecked')),
            ],
        ),
    ]
