# Generated by Django 4.1 on 2022-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_partnersform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersform',
            name='email',
            field=models.CharField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='partnersform',
            name='url',
            field=models.CharField(max_length=100, verbose_name='url'),
        ),
    ]
